{% set version = "1.0.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rclone
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RClone_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RClone/RClone_{{ version }}.tar.gz
  sha256: b2f1470faedea09ca5154ce49968d2a915fd27d3ef71b5e15cec4e8c903e8bfd

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('RClone')"           # [not win]
    - "\"%R%\" -e \"library('RClone')\""  # [win]

about:
  home: https://github.com/dbailleul/RClone
  license: GPL-2.0-or-later
  summary: R version of 'GenClone' (a computer program to analyse genotypic data, test for clonality and describe spatial clonal organization, Arnaud-Haond & Belkhir 2007, <http://wwz.ifremer.fr/clonix/content/download/68205/903914/file/GenClone2.0.setup.zip>), this package allows clone handling as 'GenClone' does, plus
    the possibility to work with several populations, MultiLocus Lineages (MLL) custom definition and use, and p-value calculation for psex statistic (probability of originating from distinct sexual events) and psex_Fis statistic (taking account of Hardy-Weinberg equilibrium departure) as 'MLGsim'/'MLGsim2' (a program for
    detecting clones using a simulation approach, Stenberg et al. 2003).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RClone
# Version: 1.0.2
# Date: 2016-05-31
# Title: Partially Clonal Populations Analysis
# Authors@R: c( person("Sophie", "Arnaud-Haond", email = "sophie.arnaud@ifremer.fr", role = "aut"), person("Diane", "Bailleul", email = "diane.bailleul.pro@gmail.com", role = c("aut", "cre")), person("Solenn", "Stoeckel", role = "ctb"))
# Author: Sophie Arnaud-Haond [aut], Diane Bailleul [aut, cre], Solenn Stoeckel [ctb]
# Maintainer: Diane Bailleul <diane.bailleul.pro@gmail.com>
# Description: R version of 'GenClone' (a computer program to analyse genotypic data, test for clonality and describe spatial clonal organization, Arnaud-Haond & Belkhir 2007, <http://wwz.ifremer.fr/clonix/content/download/68205/903914/file/GenClone2.0.setup.zip>), this package allows clone handling as 'GenClone' does, plus the possibility to work with several populations, MultiLocus Lineages (MLL) custom definition and use, and p-value calculation for psex statistic (probability of originating from distinct sexual events) and psex_Fis statistic (taking account of Hardy-Weinberg equilibrium departure) as 'MLGsim'/'MLGsim2' (a program for detecting clones using a simulation approach, Stenberg et al. 2003).
# License: GPL (>= 2.0)
# LazyLoad: yes
# Depends: R (>= 3.2.0), graphics, stats, grDevices, utils, datasets, methods
# URL: https://github.com/dbailleul/RClone
# Suggests: knitr, pander, testthat
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2016-06-06 09:59:14 UTC; Diane
# Repository: CRAN
# Date/Publication: 2016-06-06 12:57:15
